<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ship to different address_shippingAdd_0f9b79</name>
   <tag></tag>
   <elementGuidId>8c4a3db9-5185-4698-a988-ae4217387178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;shippingAddressRequired&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='shippingAddressRequired']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c21e1b27-d3d7-40ec-9e8a-cf2d4ce1207f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shippingAddressRequired</value>
      <webElementGuid>99ef2ddc-7aba-4661-b540-fb4443e05bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b5fb85b7-6596-48af-8a85-fc02bf21826a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>890c06ed-10c2-482d-b43b-ef33762b3768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Catalog&quot;)/form[1]/table[1]/tbody[1]/tr[14]/td[1]/input[1]</value>
      <webElementGuid>652d66c0-c045-4f6b-bfd3-f15bc46d972f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='shippingAddressRequired']</value>
      <webElementGuid>13ff8f62-94cc-4cfc-b05a-d87860a6da56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/table/tbody/tr[14]/td/input</value>
      <webElementGuid>243a7892-46f9-4ed2-8e21-eaf425387c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td/input</value>
      <webElementGuid>01d2e771-5c25-4eb4-ac24-1427891f59b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'shippingAddressRequired' and @type = 'checkbox']</value>
      <webElementGuid>839ea456-9540-45b6-8072-5e5f25679160</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
